name: Deploy to VPS

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Clone the code
        uses: actions/checkout@v4

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔑 Connect to the server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/rappelAnniv
            git pull origin main
            npm install
            npm run build
            pm2 restart rappelAnniv
